/// Flutter icons InterfaceIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  InterfaceIcons
///      fonts:
///       - asset: fonts/InterfaceIcons.ttf
///
///
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class InterfaceIcons {
  InterfaceIcons._();

  static const _kFontFam = 'InterfaceIcons';
  static const String _kFontPkg = "interface_icons";

  static const IconData sr_stats = IconData(
    0xe800,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_file_chart_line = IconData(
    0xe801,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_chart_pie_alt = IconData(
    0xe802,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_chart_histogram = IconData(
    0xe803,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_stats = IconData(
    0xe804,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_file_chart_line = IconData(
    0xe805,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_chart_pie_alt = IconData(
    0xe806,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_chart_histogram = IconData(
    0xe807,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_chart_pie_alt = IconData(
    0xe808,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_file_chart_line = IconData(
    0xe809,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_stats = IconData(
    0xe80a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_chart_histogram = IconData(
    0xe80b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_bolt = IconData(
    0xe80c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_bolt = IconData(
    0xe80d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_bolt = IconData(
    0xe80e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_camera = IconData(
    0xe80f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_home = IconData(
    0xe810,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_user = IconData(
    0xe811,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_camera = IconData(
    0xe812,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_home = IconData(
    0xe813,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_user = IconData(
    0xe814,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_camera = IconData(
    0xe815,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_home = IconData(
    0xe816,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_user = IconData(
    0xe817,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_thumbtack = IconData(
    0xe818,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_thunderstorm = IconData(
    0xe819,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_sun = IconData(
    0xe81a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_thumbtack = IconData(
    0xe81b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_sun = IconData(
    0xe81c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_thunderstorm = IconData(
    0xe81d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_thumbs_down = IconData(
    0xe81e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_thumbs_up = IconData(
    0xe81f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_thumbtack = IconData(
    0xe820,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_thunderstorm = IconData(
    0xe821,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_sun = IconData(
    0xe822,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_moon_stars = IconData(
    0xe823,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_moon_stars = IconData(
    0xe824,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_moon_stars = IconData(
    0xe825,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_document_signed = IconData(
    0xe826,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_document = IconData(
    0xe827,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_eclipse_alt = IconData(
    0xe828,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_document_signed = IconData(
    0xe829,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_document = IconData(
    0xe82a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_eclipse_alt = IconData(
    0xe82b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_document_signed = IconData(
    0xe82c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_document = IconData(
    0xe82d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_eclipse_alt = IconData(
    0xe82e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_document_alt = IconData(
    0xe82f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_comment_alt = IconData(
    0xe830,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_clock_five = IconData(
    0xe831,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_clock_five = IconData(
    0xe832,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_clock_five = IconData(
    0xe833,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_book_alt = IconData(
    0xe834,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_book_alt = IconData(
    0xe835,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_book_alt = IconData(
    0xe836,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_music = IconData(
    0xe837,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_music_alt = IconData(
    0xe838,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_music = IconData(
    0xe839,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_music = IconData(
    0xe83a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_music_alt = IconData(
    0xe83b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_music_alt = IconData(
    0xe83c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_folder = IconData(
    0xe83d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_add_folder = IconData(
    0xe83e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_folders = IconData(
    0xe83f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_folder = IconData(
    0xe840,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_add_folder = IconData(
    0xe841,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_folders = IconData(
    0xe842,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_folder = IconData(
    0xe843,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_add_folder = IconData(
    0xe844,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_folders = IconData(
    0xe845,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_book_open_cover = IconData(
    0xe846,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_calendar = IconData(
    0xe847,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_book_open_cover = IconData(
    0xe848,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_calendar = IconData(
    0xe849,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_book_open_cover = IconData(
    0xe84a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_calendar = IconData(
    0xe84b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_angle_circle_down = IconData(
    0xe8d8,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_angle_circle_left = IconData(
    0xe8d9,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_angle_circle_right = IconData(
    0xe8da,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_angle_double_left = IconData(
    0xe8db,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_angle_circle_up = IconData(
    0xe8dc,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_angle_double_right = IconData(
    0xe8dd,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_angle_double_small_down = IconData(
    0xe8de,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_angle_double_small_left = IconData(
    0xe8df,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_angle_double_small_right = IconData(
    0xe8e0,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_angle_double_small_up = IconData(
    0xe8e1,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_angle_down = IconData(
    0xe8e2,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_angle_right = IconData(
    0xe8e3,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_angle_left = IconData(
    0xe8e4,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_angle_small_down = IconData(
    0xe8e5,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_angle_small_left = IconData(
    0xe8e6,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_angle_small_right = IconData(
    0xe8e7,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_angle_small_up = IconData(
    0xe8e8,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_angle_square_down = IconData(
    0xe8e9,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_angle_square_left = IconData(
    0xe8ea,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_angle_square_right = IconData(
    0xe8eb,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_angle_square_up = IconData(
    0xe8ec,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_angle_up = IconData(
    0xe8ed,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_apps = IconData(
    0xe8ee,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_badge_check = IconData(
    0xe8ef,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_ban = IconData(
    0xe8f0,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_bell = IconData(
    0xe8f1,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_book_arrow_right = IconData(
    0xe8f2,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_book_bookmark = IconData(
    0xe8f3,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_bookmark = IconData(
    0xe8f4,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_caret_circle_down = IconData(
    0xe8f5,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_caret_circle_right = IconData(
    0xe8f6,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_caret_circle_up = IconData(
    0xe8f7,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_caret_down = IconData(
    0xe8f8,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_caret_left = IconData(
    0xe8f9,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_caret_quare_up = IconData(
    0xe8fa,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_caret_right = IconData(
    0xe8fb,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_caret_square_down = IconData(
    0xe8fc,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_caret_square_left_1 = IconData(
    0xe8fd,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_caret_square_left = IconData(
    0xe8fe,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_caret_square_right = IconData(
    0xe8ff,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_caret_up = IconData(
    0xe900,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_check = IconData(
    0xe901,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_clock_three = IconData(
    0xe902,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_comment_check = IconData(
    0xe903,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_comment_exclamation = IconData(
    0xe904,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_comment = IconData(
    0xe905,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_comments = IconData(
    0xe906,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_cross_circle = IconData(
    0xe907,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_cross_small = IconData(
    0xe908,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_cross = IconData(
    0xe909,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_diploma = IconData(
    0xe90a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_envelope_open_text = IconData(
    0xe90b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_envelope_open = IconData(
    0xe90c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_envelope_plus = IconData(
    0xe90d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_envelope = IconData(
    0xe90e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_exclamation = IconData(
    0xe90f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_expand = IconData(
    0xe910,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_eye_crossed = IconData(
    0xe911,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_forward = IconData(
    0xe912,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_headphones = IconData(
    0xe913,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_heart = IconData(
    0xe914,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_interface = IconData(
    0xe915,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_layers = IconData(
    0xe916,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_lock = IconData(
    0xe917,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_menu_dots_vertical = IconData(
    0xe918,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_menu_dots = IconData(
    0xe919,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_microphone = IconData(
    0xe91a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_minus_small = IconData(
    0xe91b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_minus = IconData(
    0xe91c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_moon = IconData(
    0xe91d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_pause = IconData(
    0xe91e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_pencil = IconData(
    0xe91f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_play = IconData(
    0xe920,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_quote_right = IconData(
    0xe921,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_redo = IconData(
    0xe922,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_search = IconData(
    0xe923,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_settings_sliders = IconData(
    0xe924,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_settings = IconData(
    0xe925,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_share = IconData(
    0xe926,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_skip_backward = IconData(
    0xe927,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_star = IconData(
    0xe928,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_text_check = IconData(
    0xe929,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_time_forward_ten = IconData(
    0xe92a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_time_forward = IconData(
    0xe92b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData br_time_past = IconData(
    0xe92c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_angle_circle_down = IconData(
    0xe92d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_angle_circle_left = IconData(
    0xe92e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_angle_circle_right = IconData(
    0xe92f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_angle_circle_up = IconData(
    0xe930,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_angle_double_left = IconData(
    0xe931,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_angle_double_right = IconData(
    0xe932,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_angle_double_small_down = IconData(
    0xe933,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_angle_double_small_left = IconData(
    0xe934,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_angle_double_small_right = IconData(
    0xe935,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_angle_double_small_up = IconData(
    0xe936,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_angle_down = IconData(
    0xe937,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_angle_left = IconData(
    0xe938,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_angle_right = IconData(
    0xe939,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_angle_small_down = IconData(
    0xe93a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_angle_small_left = IconData(
    0xe93b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_angle_small_right = IconData(
    0xe93c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_angle_small_up = IconData(
    0xe93d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_angle_square_down = IconData(
    0xe93e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_angle_square_left = IconData(
    0xe93f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_angle_square_right = IconData(
    0xe940,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_angle_square_up = IconData(
    0xe941,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_angle_up = IconData(
    0xe942,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_apps = IconData(
    0xe943,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_badge_check = IconData(
    0xe944,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_ban = IconData(
    0xe945,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_bell = IconData(
    0xe946,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_book_arrow_right = IconData(
    0xe947,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_book_bookmark = IconData(
    0xe948,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_bookmark = IconData(
    0xe949,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_caret_circle_down = IconData(
    0xe94a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_caret_circle_right = IconData(
    0xe94b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_caret_circle_up = IconData(
    0xe94c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_caret_down = IconData(
    0xe94d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_caret_left = IconData(
    0xe94e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_caret_quare_up = IconData(
    0xe94f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_caret_right = IconData(
    0xe950,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_caret_square_down = IconData(
    0xe951,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_caret_square_left_1 = IconData(
    0xe952,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_caret_square_left = IconData(
    0xe953,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_caret_square_right = IconData(
    0xe954,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_caret_up = IconData(
    0xe955,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_check = IconData(
    0xe956,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_clock_three = IconData(
    0xe957,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_comment_check = IconData(
    0xe958,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_comment_exclamation = IconData(
    0xe959,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_comment = IconData(
    0xe95a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_comments = IconData(
    0xe95b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_cross_circle = IconData(
    0xe95c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_cross_small = IconData(
    0xe95d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_cross = IconData(
    0xe95e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_diploma = IconData(
    0xe95f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_envelope_open_text = IconData(
    0xe960,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_envelope_open = IconData(
    0xe961,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_envelope_plus = IconData(
    0xe962,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_envelope = IconData(
    0xe963,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_exclamation = IconData(
    0xe964,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_expand = IconData(
    0xe965,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_eye_crossed = IconData(
    0xe966,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_forward = IconData(
    0xe967,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_headphones = IconData(
    0xe968,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_heart = IconData(
    0xe969,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_interface = IconData(
    0xe96a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_layers = IconData(
    0xe96b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_lock = IconData(
    0xe96c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_menu_dots_vertical = IconData(
    0xe96d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_menu_dots = IconData(
    0xe96e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_microphone = IconData(
    0xe96f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_minus_small = IconData(
    0xe970,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_minus = IconData(
    0xe971,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_moon = IconData(
    0xe972,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_pause = IconData(
    0xe973,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_pencil = IconData(
    0xe974,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_play = IconData(
    0xe975,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_quote_right = IconData(
    0xe976,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_redo = IconData(
    0xe977,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_search = IconData(
    0xe978,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_settings_sliders = IconData(
    0xe979,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_settings = IconData(
    0xe97a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_share = IconData(
    0xe97b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_skip_backward = IconData(
    0xe97c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_star = IconData(
    0xe97d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_text_check = IconData(
    0xe97e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_time_forward_ten = IconData(
    0xe97f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_time_forward = IconData(
    0xe980,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData rr_time_past = IconData(
    0xe981,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_angle_circle_down = IconData(
    0xe982,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_angle_circle_left = IconData(
    0xe983,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_angle_circle_right = IconData(
    0xe984,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_angle_circle_up = IconData(
    0xe985,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_angle_double_left = IconData(
    0xe986,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_angle_double_right = IconData(
    0xe987,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_angle_double_small_down = IconData(
    0xe988,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_angle_double_small_left = IconData(
    0xe989,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_angle_double_small_right = IconData(
    0xe98a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_angle_double_small_up = IconData(
    0xe98b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_angle_down = IconData(
    0xe98c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_angle_left = IconData(
    0xe98d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_angle_right = IconData(
    0xe98e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_angle_small_down = IconData(
    0xe98f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_angle_small_left = IconData(
    0xe990,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_angle_small_right = IconData(
    0xe991,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_angle_small_up = IconData(
    0xe992,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_angle_square_down = IconData(
    0xe993,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_angle_square_left = IconData(
    0xe994,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_angle_square_right = IconData(
    0xe995,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_angle_square_up = IconData(
    0xe996,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_angle_up = IconData(
    0xe997,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_apps = IconData(
    0xe998,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_badge_check = IconData(
    0xe999,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_ban = IconData(
    0xe99a,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_bell = IconData(
    0xe99b,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_book_arrow_right = IconData(
    0xe99c,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_book_bookmark = IconData(
    0xe99d,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_bookmark = IconData(
    0xe99e,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_caret_circle_down = IconData(
    0xe99f,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_caret_circle_right = IconData(
    0xe9a0,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_caret_circle_up = IconData(
    0xe9a1,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_caret_down = IconData(
    0xe9a2,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_caret_left = IconData(
    0xe9a3,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_caret_quare_up = IconData(
    0xe9a4,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_caret_right = IconData(
    0xe9a5,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_caret_square_down = IconData(
    0xe9a6,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_caret_square_left_1 = IconData(
    0xe9a7,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_caret_square_left = IconData(
    0xe9a8,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_caret_square_right = IconData(
    0xe9a9,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_caret_up = IconData(
    0xe9aa,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_check = IconData(
    0xe9ab,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_clock_three = IconData(
    0xe9ac,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_comment_check = IconData(
    0xe9ad,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_comment_exclamation = IconData(
    0xe9ae,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_comment = IconData(
    0xe9af,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_comments = IconData(
    0xe9b0,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_cross_circle = IconData(
    0xe9b1,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_cross_small = IconData(
    0xe9b2,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_cross = IconData(
    0xe9b3,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_diploma = IconData(
    0xe9b4,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_envelope_open_text = IconData(
    0xe9b5,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_envelope_open = IconData(
    0xe9b6,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_envelope_plus = IconData(
    0xe9b7,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_envelope = IconData(
    0xe9b8,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_exclamation = IconData(
    0xe9b9,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_expand = IconData(
    0xe9ba,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_eye_crossed = IconData(
    0xe9bb,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_forward = IconData(
    0xe9bc,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_headphones = IconData(
    0xe9bd,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_heart = IconData(
    0xe9be,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_interface = IconData(
    0xe9bf,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_layers = IconData(
    0xe9c0,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_lock = IconData(
    0xe9c1,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_menu_dots_vertical = IconData(
    0xe9c2,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_menu_dots = IconData(
    0xe9c3,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_microphone = IconData(
    0xe9c4,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_minus_small = IconData(
    0xe9c5,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_minus = IconData(
    0xe9c6,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_moon = IconData(
    0xe9c7,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_pause = IconData(
    0xe9c8,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_pencil = IconData(
    0xe9c9,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_play = IconData(
    0xe9ca,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_quote_right = IconData(
    0xe9cb,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_redo = IconData(
    0xe9cc,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_search = IconData(
    0xe9cd,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_settings_sliders = IconData(
    0xe9ce,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_settings = IconData(
    0xe9cf,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_share = IconData(
    0xe9d0,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_skip_backward = IconData(
    0xe9d1,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_star = IconData(
    0xe9d2,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_text_check = IconData(
    0xe9d3,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_time_forward_ten = IconData(
    0xe9d4,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_time_forward = IconData(
    0xe9d5,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData sr_time_past = IconData(
    0xe9d6,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData apple = IconData(
    0xf179,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData google = IconData(
    0xf1a0,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
  static const IconData whatsapp = IconData(
    0xf232,
    fontFamily: _kFontFam,
    fontPackage: _kFontPkg,
  );
}
